"""
Heading Style Fixer for DOCX
============================

This module provides utilities to fix heading styles in DOCX files generated by Pandoc.
It ensures headings are mapped to Word built-in styles (Heading 1, Heading 2, Heading 3)
and sets proper outline levels for Table of Contents generation.

Usage:
    from heading_fixer import fix_docx_headings
    fix_docx_headings("output.docx")
"""

from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
import re


class HeadingDetector:
    """Detects heading levels based on text patterns and style information."""
    
    @staticmethod
    def detect_level(paragraph):
        """
        Detect heading level from a paragraph.
        
        Rules (in order):
        1. BAB <chapter_number> → Level 1 (Chapter)
        2. ALL CAPS text (3-80 chars) → Level 2 (Section)
        3. Existing heading styles (Heading1, Heading 1, etc.) → Extract level
        
        Returns:
            int: 1, 2, or 3 for heading levels, or None if not a heading
        """
        text = paragraph.text.strip()
        
        # Rule 1: Chapter headings (BAB = Chapter in Indonesian)
        if text.startswith("BAB "):
            return 1
        
        # Rule 2: Section headings (ALL CAPS)
        if text and text.isupper() and 3 < len(text) < 80:
            return 2
        
        # Rule 3: Existing heading styles
        style_name = paragraph.style.name if paragraph.style else ""
        match = re.search(r'[Hh]eading\s*(\d)', style_name)
        if match:
            level = int(match.group(1))
            return level if 1 <= level <= 3 else None
        
        return None


class StyleApplier:
    """Applies Word built-in heading styles and sets outline levels."""
    
    HEADING_STYLES = {
        1: "Heading 1",
        2: "Heading 2",
        3: "Heading 3"
    }
    
    @staticmethod
    def apply_heading_style(paragraph, level):
        """
        Apply heading style and set outline level.
        
        Args:
            paragraph: python-docx paragraph object
            level: Heading level (1, 2, or 3)
        """
        # Apply style
        style_name = StyleApplier.HEADING_STYLES.get(level)
        if style_name:
            paragraph.style = style_name
        
        # Set outline level via XML
        pPr = paragraph._element.get_or_add_pPr()
        outlineLvl = pPr.find(qn('w:outlineLvl'))
        
        if outlineLvl is None:
            outlineLvl = OxmlElement('w:outlineLvl')
            pPr.append(outlineLvl)
        
        # w:outlineLvl is 0-indexed (0=Heading 1, 1=Heading 2, 2=Heading 3)
        outlineLvl.set(qn('w:val'), str(level - 1))


def fix_docx_headings(docx_path):
    """
    Fix heading styles in a DOCX file.
    
    This function:
    1. Detects headings based on text patterns and existing styles
    2. Applies Word built-in heading styles (Heading 1, 2, 3)
    3. Sets proper outline levels for TOC generation
    
    Args:
        docx_path (str): Path to the DOCX file
        
    Returns:
        dict: Statistics about changes made
    """
    doc = Document(docx_path)
    stats = {
        "level_1": 0,
        "level_2": 0,
        "level_3": 0,
        "total": 0
    }
    
    for paragraph in doc.paragraphs:
        level = HeadingDetector.detect_level(paragraph)
        
        if level:
            StyleApplier.apply_heading_style(paragraph, level)
            stats[f"level_{level}"] += 1
            stats["total"] += 1
    
    doc.save(docx_path)
    return stats


def print_heading_analysis(docx_path):
    """
    Print analysis of heading detection in a DOCX file.
    Useful for debugging and validation.
    
    Args:
        docx_path (str): Path to the DOCX file
    """
    doc = Document(docx_path)
    
    print(f"\n{'='*80}")
    print(f"Heading Analysis for: {docx_path}")
    print(f"{'='*80}\n")
    
    heading_count = 0
    for i, paragraph in enumerate(doc.paragraphs):
        level = HeadingDetector.detect_level(paragraph)
        
        if level:
            heading_count += 1
            text_preview = paragraph.text[:60].ljust(60)
            style = paragraph.style.name if paragraph.style else "None"
            print(f"[Heading {level}] {text_preview} | Style: {style}")
    
    print(f"\nTotal headings detected: {heading_count}")
    print(f"{'='*80}\n")


if __name__ == "__main__":
    # Test usage
    import sys
    
    if len(sys.argv) > 1:
        docx_file = sys.argv[1]
        print(f"Analyzing: {docx_file}")
        print_heading_analysis(docx_file)
        
        print("Fixing headings...")
        stats = fix_docx_headings(docx_file)
        print(f"Fixed {stats['total']} headings:")
        print(f"  - Level 1: {stats['level_1']}")
        print(f"  - Level 2: {stats['level_2']}")
        print(f"  - Level 3: {stats['level_3']}")
    else:
        print("Usage: python heading_fixer.py <docx_file>")
